baseURL = 'https://example.org/'
locale = 'en-us'
title = 'My New Hugo Project'

pluralizelisttitles = "false"

[security]
  allowContent = [ '.*' ]


[markup]
 [markup.goldmark]
  [markup.goldmark.parser]
   [markup.goldmark.parser.attribute]
    block = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1
