baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Project'

pluralizelisttitles = "false"

[markup]
 [markup.goldmark]
  [markup.goldmark.parser]
   [markup.goldmark.parser.attribute]
    block = true
  [markup.goldmark.renderer]
    unsafe = true
