baseURL = 'https://books.lukesmith.xyz/'
locale = 'en-us'
title = "Luke's Books"

pluralizelisttitles = "false"

[security]
  allowContent = [ '.*' ]

[markup]
 [markup.goldmark]
  [markup.goldmark.parser]
   [markup.goldmark.parser.attribute]
    block = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1
