#!/bin/sh

# Get a WikiSource file and preprocess it for use in the site.

# ¶

[ -z "$2" ] || pre="$2-"

w3m -dump "$1" | sed  "
	s|^\s*\([0-9]\+\)\. ↑ |[^$pre\1]: |
	s|\^\[\([0-9]\+\)\]|[^$pre\1]|
	s|^\([0-9]\+\)\. |\1\\\. |
	s|[”“]|\"|g
	s|[‘’]|'|g
	/^Footnotes$/d
	/^\[edit\]$/d
	/^\*$/Q

		" | sed -e '1,/^→$/ d'
